{% set name = "napari-nd2-folder-viewer" %}
{% set version = "0.0.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/napari-nd2-folder-viewer-{{ version }}.tar.gz
  sha256: d5534ed0d98467b7690922901ffb87ee9d099ade9b3a383a4597ff1da4f1fdfa

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.8
    - setuptools-scm
  run:
    - dask-core
    - desert
    - julian
    - magicgui
    - marshmallow
    - napari
    - napari-animation
    - nd2
    - numpy
    - openpyxl
    - pandas
    - python >=3.8
    - pyyaml
    - qtpy
    - scikit-learn

test:
  imports:
    - napari_nd2_folder_viewer
  commands:
    - pip list
    - pip check
  requires:
    - pip

about:
  home: https://github.com/gatoniel/napari-nd2-folder-viewer
  summary: Look through separate nd2 files in one viewer.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - goanpeca
    - jaimergp
