{% set name = "napari-nd2-folder-viewer" %}
{% set version = "0.0.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/napari-nd2-folder-viewer-{{ version }}.tar.gz
  sha256: f55e0919bc21a19e49da4ec28c582c5d7e2794afa1af4aec48fcc1aedf0d3c46

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.8
    - setuptools_scm
  run:
    - dask-core
    - desert
    - julian
    - magicgui
    - marshmallow
    - napari
    - nd2
    - numpy
    - openpyxl
    - pandas
    - python >=3.8
    - pyyaml
    - qtpy

test:
  imports:
    - napari_nd2_folder_viewer
  commands:
    - pip list
    - pip check
  requires:
    - pip

about:
  home: https://github.com/gatoniel/napari-nd2-folder-viewer
  summary: Look through separate nd2 files in one viewer.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - goanpeca
    - jaimergp
